language: r
cache: packages
pandoc_version: 1.19.2.1

r_packages:
  - devtools

r_github_packages:
  - moderndive/moderndive
  - andrewpbray/infer@660957fbe3393bebf66dc766ff97abca1920c8bb

before_script:
  - chmod +x ./_build.sh
#  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
#  - ./_deploy.sh

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  keep-history: true
  github_token: $MODERNDIVE_GITHUB_PAT
  repo: moderndive/moderndive_book
  target_branch: gh-pages
